### PR TITLE
i18n example

### PR DESCRIPTION
**Pull request by immenor**
I added i18next which is a library for handling internationalization. 

Each language has its own json file in the locales folder. For example english is in locales/en/translation.json
i18n looks for a file of this name in a directory matching the name of the language. You can even define something more specific, for example en-US for US english. If that doesn't exist, it will fall back to 'en'. The naming convention follows ISO standard naming for languages.

In order to load this file, it uses XHR and requires cross domain requests, so when you are editing on local, you will need to host on localhost in order for it to work. I used an app called CodeKit to do this locally since I didn't see anything for setting up a dev environment inside this git. 

For the purposes of this example I just added the needed libraries from cdn links, and only on the app.html page. Really this should be defined in a way so that it is shared across all the pages to reduce duplication.

I added some translations for the navigation and header title so you could see how this system works.

I made a new file for i18n that will talk to i18n directly. To activate it via jquery for a specific page, I call this:

`<script>
		i18nManager(function() {
			$('body').localize();
		})
	</script>`

To add a string to an element, add `data-i18n="key"` to the html element, where key is the key path in the translations.json.

You can choose where on the page to apply localization too. We want the whole page, so I set it to body. This passes this function to the i18n library and runs those changes whenever the language changes. You could also run this code inside the i18n js file, and it would apply to the body tag of any page that includes this js file.

i18next also detects the language from the browser on load, and uses that by default if translations exist.

For more info on i18next: https://www.i18next.com/
I am also using a jquery plugin for i18next which lets you have the attributes on html tags.

### CODE REVIEW

**Comment by amilkh** [comment]
We are thinking to use vue.js since one of developers thought this method requires hardcoding for every language, is it true?

**Comment by immenor** [comment]
I think using Vue.js is a great idea. This app is in desperate need of a front-end framework. But even if you're using vue.js, you still will need an i18n plugin. But the you won't need to apply the js to each page, and you can reduce duplication. Highly recommend using a front-end framework. i18next supports vue js https://github.com/panter/vue-i18next

**Comment by tracylihuizhang** [comment]
can this be run on github static page? or do we need a server to run locally?
Amil says requirement right now is that it can run on github pages.

**Comment by immenor** [comment]
My understanding is that this should still work with github pages, since it supports CORS. You will might need to tweak the load path. In your local environment you will need a server for development, as opposed to just opening the HTML file.

**Comment by amilkh** [comment]
I see ! Hmm it does complicate our local workflow a bit, but I guess if it's only option, it's fine. We'll probably replace to vue js within a week or two, seems like.

**Comment by immenor** [comment]
it is very easy to create a local server of a folder. If you can't include it in your workflow, that is a larger issue. When you decide to use vue.js you will without a doubt need a more proper setup that includes a local development environment. I think it is important to invest in making these changes sooner rather than later.

**Comment by amilkh** [comment]
yeah! if I merge this now, will it just work on the website?
for the time being this can be a good change.

and then later we can do the more proper refactoring

**Comment by immenor** [comment]
It should work, but I haven't tested it on github pages so would have to try it and make sure that the loadPath works. If you want to try it out first, we can put these changes in an alternate html file and push that to see how it works.

**Comment by amilkh** [comment]
Okay I'm asking Tracy to try, for me though I'll probably call it a night
soon

2020年7月15日(水) 午後9:55 Canyon Boak <notifications@github.com>:

**Comment by immenor** [comment]
Sounds good. I did some googling previously and had found other examples of people making cross-domain requests on github pages, which is why I think it should be possible. Like I said though, you should test it, because I haven't tried this on github pages so I can't say for sure without trying. Its possible that the sub-domain will result in it needing a different loadPath.

**Comment by amilkh** [comment]
merged as https://github.com/virufy/virufy.github.io/blob/master/app-translation.html !!

**Comment by amilkh** [comment]
https://virufy.org/app-translation

**Pull request merged**
