### PR TITLE
form update

### PR DESCRIPTION
**Pull request by nikrasiya**
Changed none to uncheck all other checkboxes

### CODE REVIEW

**Comment by amilkh** [comment]
Awesome, quick work!!
could you please update the pull request to not have the white space changes? Kind of hard to see what changed

**Comment by nikrasiya** [comment]
@amilkh Check now!

**Comment by amilkh** [comment]
thanks! @vivianross06 can you review it?

**Comment by amilkh** [comment]
looks much better! before final merge may be good to keep whitespace indent consistent across entire file

image

**Pull request merged**
